spring:
  application:
    name: trade
  datasource:
    url: jdbc:h2:mem:crypto_trade_db
    spring.datasource.driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
app:
  service:
    aggregation:
      source:
        binance: https://api.binance.com/api/v3/ticker/bookTicker
        houbi: https://api.huobi.pro/market/tickers